title: "Cloud Six Doku"
description: "Dokumentation zu Services der Cloud Six GmbH"
theme: just-the-docs
color_scheme: "dark"

url: https://just-the-docs.github.io

aux_links:
  View on GitHub: https://github.com/Cloud-Six-GmbH/docs.cloud6.tech
